In [4]:
import numpy as np
np.empty(2)


array([2.66291888e+89, 7.58121354e-28])

In [6]:
np.linspace(0, 10, num=6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [36]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [37]:
b = a
b

array([1, 2, 3, 4, 5, 6])

In [2]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6],[7, 8]])
np.concatenate((x, y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [71]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [72]:
b = np.expand_dims(a, axis=0)
b

array([[1, 2, 3, 4, 5, 6]])

array([ 6,  7,  8,  9, 10, 11, 12])

In [87]:
import numpy as np

mark2 = np.asarray([55, 88, 78, 90, 79, 94]).reshape(2,-1)
mark2

array([[55, 88, 78],
       [90, 79, 94]])

In [93]:
import numpy as np

arr=np.asarray([55, 88, 78, 90, 79, 94]).reshape(2, -1)
arr

array([[55, 88, 78],
       [90, 79, 94]])

In [107]:
import numpy as np

def percentile_array_columns(myArray, perc):     
        print(np.percentile(myArray,perc,axis=0))
    
percentile_array_columns(np.asarray([55, 88, 78, 90, 79, 94]).reshape(2, -1),60)

[76.  84.4 87.6]
