<a href="https://colab.research.google.com/github/BasilJohn/CE888/blob/main/lab6/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Imports
import pandas as pd
import numpy as np

In [54]:
#Load Data
col_names = ['JokeCounts'] + [f'Joke{num + 1}' for num in range(100)]

#Replace 99.00 with NAN during data load
df_before_NA = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv', 
                      header=None, names=col_names)

df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv', 
                      header=None, names=col_names, na_values=["99.00"])

JokeCounts  Joke1  Joke2  Joke3  Joke4  Joke5  Joke6  Joke7  Joke8  \
0            74.0  -7.82   8.79  -9.66  -8.16  -7.52  -8.50  -9.85   4.17   
1           100.0   4.08  -0.29   6.36   4.37  -2.38  -9.66  -0.73  -5.34   
2            49.0    NaN    NaN    NaN    NaN   9.03   9.27   9.03   9.27   
3            48.0    NaN   8.35    NaN    NaN   1.80   8.16  -2.82   6.21   
4            91.0   8.50   4.61  -4.17  -5.39   1.36   1.60   7.04   4.61   
...           ...    ...    ...    ...    ...    ...    ...    ...    ...   
24978       100.0   0.44   7.43   9.08   2.33   3.20   6.75  -8.79  -0.53   
24979        91.0   9.13  -8.16   8.59   9.08   0.87  -8.93  -3.50   5.78   
24980        39.0    NaN    NaN    NaN    NaN  -7.77    NaN   6.70  -6.75   
24981        37.0    NaN    NaN    NaN    NaN  -9.71    NaN   4.56  -8.30   
24982        72.0   2.43   2.67  -3.98   4.27  -2.28   7.33   2.33   4.56   

       Joke9  ...  Joke91  Joke92  Joke93  Joke94  Joke95  Joke96  Joke97  \
0      -8.98  ...    2.82     NaN     NaN     NaN     NaN     NaN   -5.63   
1       8.88  ...    2.82   -4.95   -0.29    7.86   -0.19   -2.14    3.06   
2        NaN  ...     NaN     NaN     NaN    9.08     NaN     NaN     NaN   
3        NaN  ...     NaN     NaN     NaN    0.53     NaN     NaN     NaN   
4      -0.44  ...    5.19    5.58    4.27    5.19    5.73    1.55    3.11   
...      ...  ...     ...     ...     ...     ...     ...     ...     ...   
24978  -8.74  ...    8.83   -1.21    9.22   -6.70    8.45    9.03    6.55   
24979  -8.11  ...   -1.17   -5.73   -1.46    0.24    9.22   -8.20   -7.23   
24980    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
24981    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
24982   6.75  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

       Joke98  Joke99  Joke100  
0         NaN     NaN      NaN  
1        0.34   -4.32     1.07  
2         NaN     NaN      NaN  
3         NaN     NaN      NaN  
4        6.55    1.80     1.60  
...       ...     ...      ...  
24978    8.69    8.79     7.43  
24979   -8.59    9.13     8.45  
24980     NaN     NaN      NaN  
24981     NaN     NaN      NaN  
24982     NaN     NaN      NaN  

[24983 rows x 101 columns]

In [55]:
# The first column gives the number of jokes rated by that user. 
#The next 100 columns give the ratings for jokes 01 - 100.
# Drop first column and save it in a separate variable
df_copy = df.copy()
df2 = df_copy.copy()
df_just_jokes=df_copy.iloc[: , 1:]
df_joke_total_counts = df.iloc[: , :1]
df_copy_beforeNA=df_before_NA.iloc[: , 1:]

In [ ]:
#Use pandas to find the best- and the worst-rated jokes

In [81]:
arr=df_copy_beforeNA.values
print(arr.shape)
arr

(24983, 100)


array([[-7.82,  8.79, -9.66, ..., 99.  , 99.  , 99.  ],
       [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       ...,
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [ 2.43,  2.67, -3.98, ..., 99.  , 99.  , 99.  ]])

In [57]:
#Modify and use the helper function provided in the helper_function notebook 
#(or create your own) to label 10% of the dataset cells that are not NaNs as 99. 
#This is your validation set. 
#Keep the the actual values of the cells so you can use them later (as done in the example 
#of the helper_function notebook).
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])
  


In [58]:
  new_arr, idx = replace(arr, 0.1)

In [59]:
arr[idx[0][0], idx[1][0]]

4.51

In [60]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [61]:
#Use latent factor modeling (with 2 latent factors) to infer the hidden ratings of the users 
#(they are labeled as "99" in the dataset) on the training set. 
#You will have to modify at least one line in the provided sgd() function for this (and probably 2, 
#depending on your variable names).
#Iterations in sgd will take a long time to run: you can (and should) use low numbers. Try something like 10.
#You can interrupt at any point the execution of this function, because the values are updated in each iteration, 
#so if you interrupt execution you can use the latent_user_preferences and latent_item_features.

n_latent_factors = 2

user_ratings = new_arr
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))


In [83]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=50):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if rating != 99:
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10) == 0:
            print(mse)

In [84]:
sgd()

18.458440308448203
17.39804237828419


KeyboardInterrupt: ignored

In [65]:
 #Calculate the performance (e.g., MSE) of the algorithm on the validation dataset
original_data = arr
assert len(idx[0]) == len(idx[1])
validation_size = len(idx[0])
errors = []
for i in range(validation_size):
  user_id = idx[0][i]
  joke_id = idx[1][i]
  prediction_rating = predict_rating(user_id, joke_id)
  real_rating = original_data[user_id][joke_id]
  error = prediction_rating - real_rating
  errors.append(error)
mse = (np.array(errors) ** 2).mean()
print('Validation MSE:', mse)

Validation MSE: 19.180937822767966


In [67]:
#make predictions for the test dataset.
new_data = np.zeros(original_data.shape)
rows, columns = original_data.shape
for user_id in range(rows):
  for joke_id in range(columns):
    if original_data[user_id][joke_id] == 99:
      new_data[user_id][joke_id] = predict_rating(user_id, joke_id)
    else:
      new_data[user_id][joke_id] = original_data[user_id][joke_id]

In [68]:
new_data

array([[-7.82      ,  8.79      , -9.66      , ..., -1.45932918,
        -2.14989714, -1.40984563],
       [ 4.08      , -0.29      ,  6.36      , ...,  0.34      ,
        -4.32      ,  1.07      ],
       [ 5.92112334,  6.16304963,  6.35401255, ...,  6.55003921,
         5.31362855,  7.34957042],
       ...,
       [ 0.50907518,  0.60734616,  0.78262571, ...,  0.44911428,
         0.55270367,  0.45955284],
       [ 0.66790646,  0.63875663,  0.54456368, ...,  0.82192367,
         0.52954578,  0.95458551],
       [ 2.43      ,  2.67      , -3.98      , ...,  3.69730583,
         2.6878997 ,  4.22201049]])

In [82]:
means = np.mean(new_data, axis=0)

max_joke = -9999999999
max_joke_index = -1
min_joke = 99999999999
min_joke_index = -1

for i in range(len(means)):
  if means[i] > max_joke:
    max_joke = means[i]
    max_joke_index = i
  elif means[i] < min_joke:
    min_joke = means[i]
    min_joke_index = i

print(f'The best {max_joke_index + 1}, with a mean rating of: {max_joke}')
print(f'The worst{min_joke_index + 1}, with a mean rating of: {min_joke}')

The best 50, with a mean rating of: 3.6650331855321037
The worst16, with a mean rating of: -3.104217277268334


In [85]:
df2.iloc[14389, 62]

9.03

In [87]:
movie_items = pd.read_excel('movies_latent_factors.xlsx', sheet_name='Items')
movie_users = pd.read_excel('movies_latent_factors.xlsx', sheet_name='Users')

In [108]:
movie_items

Movie ID                                              Title   Factor1  \
0         11          Star Wars: Episode IV - A New Hope (1977) -1.521848   
1         12                                Finding Nemo (2003) -0.342185   
2         13                                Forrest Gump (1994) -2.240888   
3         14                             American Beauty (1999) -0.634531   
4         22  Pirates of the Caribbean: The Curse of the Bla...  0.517348   
..       ...                                                ...       ...   
95      9806                             The Incredibles (2004)  0.159967   
96     10020                        Beauty and the Beast (1991)  1.286288   
97     36657                                       X-Men (2000)  0.811901   
98     36658                            X2: X-Men United (2003)  1.161006   
99     36955                                   True Lies (1994)  1.734008   

     Factor2   Factor3   Factor4   Factor5   Factor6   Factor7   Factor8  \
0  -1.038507  2.027269  0.247933 -0.594548  2.513260 -1.848910  0.476710   
1  -0.296586 -0.385962  2.443297 -1.097015 -0.619465  0.572887  0.329516   
2  -0.438815 -2.275177  0.614548  0.904469  0.711919 -0.420876  1.302036   
3   2.186059 -0.066681  0.086197  0.517558 -0.185319 -0.412352  0.063841   
4  -1.456763  0.369161  0.073903 -0.098332 -0.594722  0.828888  0.033626   
..       ...       ...       ...       ...       ...       ...       ...   
95 -0.051123  0.311183  1.841867 -1.952736 -0.836041  0.639252 -0.413082   
96  0.004957 -0.157640  2.579640 -0.042687 -0.256582 -0.007971  0.458163   
97 -0.893280  0.668953 -0.885074 -1.070468 -0.973154 -0.037449 -0.925609   
98 -0.715613  0.712633 -0.688808 -0.717785 -1.007047 -0.267268 -0.802322   
99  0.265436 -0.003391 -0.491754 -0.322739  0.850165 -0.150377 -0.075895   

     Factor9  Factor10  Factor11  Factor12  Factor13  Factor14  Factor15  
0  -0.224146 -0.760681 -0.973915  0.862379  0.403861  1.129616 -0.248806  
1  -0.712228  0.323554 -0.561948 -0.142405 -0.564415  0.506876  1.274993  
2  -0.868418 -0.160122  0.633667  0.133138 -0.330276 -2.209004 -0.419092  
3   0.075937 -0.577682  0.526803 -1.465557 -0.819682  0.549010 -0.681191  
4  -0.707414  0.717877  1.394326 -0.786986  1.429191  0.855746 -2.292566  
..       ...       ...       ...       ...       ...       ...       ...  
95 -0.310868  0.448225 -0.846044 -0.158192 -0.649164  0.045580  1.017861  
96  0.091394  0.323339 -0.862833 -0.508185  0.994535  0.868700 -0.487076  
97 -0.122112 -0.328822 -0.163103 -0.307299  0.642105 -1.355542  0.067790  
98 -0.249239 -0.540419 -0.291422 -0.240216  0.290714 -1.217250 -0.288130  
99  1.373386  0.934767  0.489299 -0.062678  0.333703 -0.223382 -0.022599  

[100 rows x 17 columns]

In [91]:
movie_users.head()

User   Factor1   Factor2   Factor3   Factor4   Factor5   Factor6   Factor7  \
0  4768 -0.204024  0.161079 -0.090447  0.138495 -0.162934  0.163894  0.051502   
1   156 -0.189652 -0.178979 -0.091490 -0.000823 -0.032646  0.177209 -0.098123   
2  5323 -0.115308 -0.090886 -0.053129  0.018472 -0.068081 -0.004828  0.113005   
3   174 -0.227462 -0.272532 -0.017231  0.054324  0.214755 -0.072639 -0.033122   
4  4529 -0.014616 -0.102218 -0.107935  0.155784 -0.123362 -0.118228 -0.013549   

    Factor8   Factor9  Factor10  Factor11  Factor12  Factor13  Factor14  \
0 -0.088582  0.126829  0.065967  0.085008  0.355404  0.007108 -0.118663   
1 -0.068283 -0.011575  0.120866 -0.009931 -0.048606  0.045916  0.113671   
2  0.102107  0.034758  0.000693 -0.073712 -0.019460  0.108372  0.054471   
3 -0.086508 -0.131479  0.180403  0.095890 -0.082396  0.036767 -0.165438   
4 -0.050622  0.058698 -0.159600 -0.142382 -0.132836 -0.039897  0.129063   

   Factor15  
0 -0.039125  
1  0.179873  
2 -0.109552  
3  0.050692  
4  0.102669

In [107]:
movie_users


User   Factor1   Factor2   Factor3   Factor4   Factor5   Factor6  \
0   4768 -0.204024  0.161079 -0.090447  0.138495 -0.162934  0.163894   
1    156 -0.189652 -0.178979 -0.091490 -0.000823 -0.032646  0.177209   
2   5323 -0.115308 -0.090886 -0.053129  0.018472 -0.068081 -0.004828   
3    174 -0.227462 -0.272532 -0.017231  0.054324  0.214755 -0.072639   
4   4529 -0.014616 -0.102218 -0.107935  0.155784 -0.123362 -0.118228   
5    783 -0.020301 -0.031919 -0.036955  0.033690  0.000174 -0.003178   
6   3878 -0.091462  0.215879 -0.180453  0.085408 -0.321094  0.227947   
7    768  0.000819 -0.009229 -0.019228  0.002703  0.012869  0.006655   
8   4469 -0.030528 -0.011537 -0.042822 -0.014378  0.031338  0.012297   
9   1882 -0.083093 -0.029160  0.013748  0.022716 -0.062732 -0.080670   
10  4997 -0.185443 -0.276496 -0.781275 -0.240506  0.029611 -0.271814   
11  2067 -0.083242  0.181171 -0.344267 -0.019713 -0.243199  0.039220   
12  3806 -0.042344 -0.040755 -0.055720 -0.073726  0.018203  0.091940   
13  2848 -0.113283 -0.098942 -0.040393  0.042180 -0.041068 -0.039568   
14  4433 -0.298760 -0.290228 -0.160120  0.156277 -0.055364 -0.434205   
15  3519 -0.068454  0.020090  0.039336  0.002958 -0.018140  0.006501   
16  5338 -0.061259  0.014661  0.011412  0.001727  0.064996 -0.078448   
17  3947 -0.022340 -0.115285 -0.136980  0.038593 -0.003029  0.071770   
18  4373 -0.136550 -0.089406 -0.235399  0.120585 -0.168168  0.129990   
19  2092 -0.121763  0.011065 -0.037121  0.032568  0.017570  0.095802   
20   525 -0.040290  0.014383 -0.098967 -0.018957  0.012388  0.035546   
21  4327  0.008227  0.073899 -0.323967  0.131203 -0.320862  0.054997   
22  3048 -0.320315  0.078290 -0.083182 -0.221577 -0.078184 -0.145306   
23  2665 -0.076167 -0.006064 -0.001902 -0.053641  0.021751  0.048207   
24  4940 -0.113099  0.047643 -0.053024  0.024834  0.010643 -0.012051   

     Factor7   Factor8   Factor9  Factor10  Factor11  Factor12  Factor13  \
0   0.051502 -0.088582  0.126829  0.065967  0.085008  0.355404  0.007108   
1  -0.098123 -0.068283 -0.011575  0.120866 -0.009931 -0.048606  0.045916   
2   0.113005  0.102107  0.034758  0.000693 -0.073712 -0.019460  0.108372   
3  -0.033122 -0.086508 -0.131479  0.180403  0.095890 -0.082396  0.036767   
4  -0.013549 -0.050622  0.058698 -0.159600 -0.142382 -0.132836 -0.039897   
5   0.054474  0.045424 -0.053308  0.003437 -0.041750  0.059725 -0.021647   
6   0.053767  0.038017  0.097141 -0.139872  0.029253  0.214467  0.189250   
7   0.007687  0.018747  0.014705 -0.009256 -0.010116 -0.010051 -0.002108   
8  -0.000038 -0.010264 -0.006781 -0.019950 -0.014435  0.010926  0.024400   
9  -0.019723  0.013253 -0.091305 -0.090687  0.030638 -0.113364 -0.021325   
10 -0.056266 -0.111825 -0.290910 -0.255087 -0.098079  0.103116 -0.100563   
11 -0.092086  0.114808 -0.036472  0.042386 -0.186812 -0.127038  0.176661   
12  0.123959 -0.157403 -0.020388  0.082493  0.223057 -0.040915 -0.130308   
13  0.018291 -0.191254  0.218912  0.017262 -0.087468  0.036894  0.067105   
14 -0.089259  0.252211 -0.107413 -0.088591  0.121157  0.071371 -0.415598   
15 -0.108526  0.025045  0.056334 -0.031291 -0.035533  0.005171  0.005546   
16  0.059510  0.017402 -0.040234 -0.073409 -0.016323  0.031774 -0.062413   
17 -0.146675 -0.285724 -0.044472 -0.054032  0.064019 -0.045329 -0.111919   
18 -0.035084 -0.324028  0.087531  0.045290  0.207850 -0.028972 -0.175184   
19  0.120238 -0.048410  0.008829  0.121778  0.093783  0.044754 -0.003087   
20  0.000903  0.012835 -0.021080  0.018742 -0.050483 -0.025394  0.034079   
21  0.060751  0.162314  0.044612 -0.232241  0.094986 -0.106570 -0.051692   
22 -0.020166  0.124409 -0.063425  0.004726  0.009683  0.028016 -0.018100   
23 -0.083980  0.146907 -0.057422  0.006085  0.063240  0.086562 -0.132328   
24 -0.049150  0.006252  0.020429  0.004349  0.028372  0.010227 -0.008233   

    Factor14  Factor15  
0  -0.118663 -0.039125  
1   0.113671  0.179873  
2   0.054471 -0.109552  
3  -0.165438  0.050692  
4   0.129063  0.102669  
5   

In [113]:
movie_items

Movie ID                                              Title   Factor1  \
0         11          Star Wars: Episode IV - A New Hope (1977) -1.521848   
1         12                                Finding Nemo (2003) -0.342185   
2         13                                Forrest Gump (1994) -2.240888   
3         14                             American Beauty (1999) -0.634531   
4         22  Pirates of the Caribbean: The Curse of the Bla...  0.517348   
..       ...                                                ...       ...   
95      9806                             The Incredibles (2004)  0.159967   
96     10020                        Beauty and the Beast (1991)  1.286288   
97     36657                                       X-Men (2000)  0.811901   
98     36658                            X2: X-Men United (2003)  1.161006   
99     36955                                   True Lies (1994)  1.734008   

     Factor2   Factor3   Factor4   Factor5   Factor6   Factor7   Factor8  \
0  -1.038507  2.027269  0.247933 -0.594548  2.513260 -1.848910  0.476710   
1  -0.296586 -0.385962  2.443297 -1.097015 -0.619465  0.572887  0.329516   
2  -0.438815 -2.275177  0.614548  0.904469  0.711919 -0.420876  1.302036   
3   2.186059 -0.066681  0.086197  0.517558 -0.185319 -0.412352  0.063841   
4  -1.456763  0.369161  0.073903 -0.098332 -0.594722  0.828888  0.033626   
..       ...       ...       ...       ...       ...       ...       ...   
95 -0.051123  0.311183  1.841867 -1.952736 -0.836041  0.639252 -0.413082   
96  0.004957 -0.157640  2.579640 -0.042687 -0.256582 -0.007971  0.458163   
97 -0.893280  0.668953 -0.885074 -1.070468 -0.973154 -0.037449 -0.925609   
98 -0.715613  0.712633 -0.688808 -0.717785 -1.007047 -0.267268 -0.802322   
99  0.265436 -0.003391 -0.491754 -0.322739  0.850165 -0.150377 -0.075895   

     Factor9  Factor10  Factor11  Factor12  Factor13  Factor14  Factor15  
0  -0.224146 -0.760681 -0.973915  0.862379  0.403861  1.129616 -0.248806  
1  -0.712228  0.323554 -0.561948 -0.142405 -0.564415  0.506876  1.274993  
2  -0.868418 -0.160122  0.633667  0.133138 -0.330276 -2.209004 -0.419092  
3   0.075937 -0.577682  0.526803 -1.465557 -0.819682  0.549010 -0.681191  
4  -0.707414  0.717877  1.394326 -0.786986  1.429191  0.855746 -2.292566  
..       ...       ...       ...       ...       ...       ...       ...  
95 -0.310868  0.448225 -0.846044 -0.158192 -0.649164  0.045580  1.017861  
96  0.091394  0.323339 -0.862833 -0.508185  0.994535  0.868700 -0.487076  
97 -0.122112 -0.328822 -0.163103 -0.307299  0.642105 -1.355542  0.067790  
98 -0.249239 -0.540419 -0.291422 -0.240216  0.290714 -1.217250 -0.288130  
99  1.373386  0.934767  0.489299 -0.062678  0.333703 -0.223382 -0.022599  

[100 rows x 17 columns]

In [115]:
copy_items = movie_items.drop(['Movie ID','Title'], axis=1)
copy_users = movie_users.drop(['User'], axis=1)

users_pref= copy_users.values
items_lf= copy_items.values

ratings = users_pref.dot(items_lf.T)
ratings_df= pd.DataFrame(ratings)

In [114]:
us_id = movie_users['User'].values
it_id = movie_items['Movie ID'].values

resx =np.where(us_id == 783)
resy=np.where(it_id == 745)
print(resx, resy)

(array([5]),) (array([60]),)


In [116]:
ratings_df.iloc[resx[0],resy[0]]


60
5 -0.093629

In [118]:
resx =np.where(us_id == 5323)
resy=np.where(it_id == 453)
print(resx, resy)
ratings_df.iloc[resx[0],resy[0]]


(array([2]),) (array([39]),)


39
2  0.18164

In [119]:
rec=np.where(us_id == 4997)
print(rec)

(array([10]),)


In [120]:
ratings_df.iloc[10,]

0    -1.218669
1     0.253885
2     1.916883
3    -0.343168
4    -0.243266
        ...   
95   -0.365399
96   -0.830354
97    0.031380
98   -0.000738
99   -1.247069
Name: 10, Length: 100, dtype: float64

In [124]:
c1 = ratings_df.iloc[10,0]
c2 = ratings_df.iloc[10,1]
c3 = ratings_df.iloc[10,2]
for i in ratings_df.columns:
  if ratings_df.iloc[10,i]>c1:
    c3 = c2
    c2 = c1
    c1 = ratings_df.iloc[10,i]
    c2 
  print(c2)

0.25388510376213097
-1.2186685577077239
0.25388510376213097
0.25388510376213097
0.25388510376213097
0.25388510376213097
0.25388510376213097
0.25388510376213097
0.25388510376213097
0.25388510376213097
1.9168827074352828
1.9168827074352828
1.9168827074352828
1.9168827074352828
1.9168827074352828
1.9168827074352828
1.9168827074352828
1.9168827074352828
1.9168827074352828
1.9168827074352828
1.9168827074352828
1.9168827074352828
1.9168827074352828
1.9168827074352828
1.9168827074352828
1.9168827074352828
1.9168827074352828
1.9168827074352828
1.9168827074352828
1.9168827074352828
1.9168827074352828
1.9168827074352828
1.9168827074352828
2.1404039215671857
2.1404039215671857
2.1404039215671857
2.1404039215671857
2.1404039215671857
2.1404039215671857
2.170987691258477
2.170987691258477
2.170987691258477
2.170987691258477
2.170987691258477
2.170987691258477
2.170987691258477
2.170987691258477
2.170987691258477
2.170987691258477
2.170987691258477
2.170987691258477
2.170987691258477
2.1709876912584